PROJ_NAME = blinky

SRCS     += stm32f4_discovery.c
SRCS     += stm32f4xx_hal.c
SRCS     += stm32f4xx_hal_i2c.c
SRCS     += stm32f4xx_hal_rcc.c
SRCS     += stm32f4xx_hal_gpio.c
SRCS     += stm32f4xx_hal_cortex.c
SRCS     += stm32f4xx_hal_dma.c
SRCS     += stm32f4xx_hal_spi.c

include ../../Makefile.include

