PROJ_NAME = blinky

SRCS     += stm32f4xx_it.c
#SRCS     += stm32f4_discovery.c
SRCS     += stm32f4xx_hal.c
SRCS     += stm32f4xx_hal_rcc.c
SRCS     += stm32f4xx_hal_gpio.c
SRCS     += stm32f4xx_hal_cortex.c

include ../../Makefile.include

